#-----------------------------------
# TESTE DE TABELAS E CÓDIGOS UNICODE
#-----------------------------------

from colorama import Fore,Style

print("COMANDOS NO VIM!")
print('┌ = Ctrl + v + u + 250C')
print('└ = Ctrl + v + u + 2514')
print('┐ = Ctrl + v + u + 2510')
print('┘ = Ctrl + v + u + 2518')
print('─ = Ctrl + v + u + 2500')
print('\n')
print(Fore.GREEN,'┌─────────────────┐')
print(Fore.GREEN,'| GREEN TUI TITLE |')
print(Fore.GREEN,'└─────────────────┘')
print(Style.RESET_ALL)
print('\n')
print(Fore.RED,'┌─────────────────┐')
print(Fore.RED,'| RED TUI TITLE   |')
print(Fore.RED,'└─────────────────┘')
print(Style.RESET_ALL)
print('\n')
print(Fore.BLUE,'┌─────────────────┐')
print(Fore.BLUE,'| BLUE TUI TITLE  |')
print(Fore.BLUE,'└─────────────────┘')
print(Style.RESET_ALL)
print('\n')
print(Fore.YELLOW,'┌──────────────────┐')
print(Fore.YELLOW,'| YELLOW TUI TITLE |')
print(Fore.YELLOW,'└──────────────────┘')
print(Style.RESET_ALL)
print('\n')
print(Fore.MAGENTA,'┌───────────────────┐')
print(Fore.MAGENTA,'| MAGENTA TUI TITLE |')
print(Fore.MAGENTA,'└───────────────────┘')
print(Style.RESET_ALL)
print('\n')
print(Fore.CYAN,'┌─────────────────┐')
print(Fore.CYAN,'| CYAN TUI TITLE  |')
print(Fore.CYAN,'└─────────────────┘')
print(Style.RESET_ALL)
print('\n')
print(Fore.WHITE,'┌─────────────────┐')
print(Fore.WHITE,'| WHITE TUI TITLE |')
print(Fore.WHITE,'└─────────────────┘')
print(Style.RESET_ALL)

